server:
  # use workers < nCPUs
  workers: 4
  # latency warning, Î¼s, 50000 = 50ms
  latency_warn: 50000
  # data stream queue, per client (server buffer)
  # larger data queue - more ops/sec for clients, but higher latency
  data_queue: 1024
  max_topic_depth: 64
  # max topic length, for bulk requests - total request length + 1 byte per topic
  max_topic_length: 1024
  # max pub frame size (topic + data, bytes)
  max_pub_size: 1100000
  pid_file: /tmp/psrtd.pid
  bind_stats: 0.0.0.0:2884
  # remove for free version
  license: /opt/workstuff/psrt-license.key
proto:
  bind: 0.0.0.0:2883
  bind_udp: 0.0.0.0:2883
  # max udp frame size
  udp_frame_size: 8192
  tls_cert: certs/server.crt
  # only RSA private keys are supported
  tls_key: certs/server.key
  # allow communcations without TLS
  allow_no_tls: true
  timeout: 5
auth:
  allow_anonymous: true
  password_file: psrt-passwd
  acl: acl.yml
cluster:
  config: cluster.yml
