server:
  # use workers < nCPUs
  workers: 4
  # latency warning, Î¼s, 500000 = 500ms
  latency_warn: 500000
  # data stream queue, per client (server buffer)
  # larger data queue - more ops/sec for clients, but higher latency
  data_queue: 1024
  max_topic_depth: 64
  # max topic length, for bulk requests - total request length + 1 byte per topic
  max_topic_length: 1000000
  # max pub frame size (topic + data, bytes)
  max_pub_size: 1100000
  pid_file: /tmp/psrtd.pid
  bind_stats: 0.0.0.0:8880
  # remove for free version
  license: /opt/workstuff/psrt-license.key
proto:
  bind:
    - 0.0.0.0:2873
    - /tmp/psrt.sock
  bind_udp: 0.0.0.0:2873
  # max udp frame size
  udp_frame_size: 8192
  # for TLS: specify either PKCS12 (not supported with FIPS) or cert + key
  #tls_pkcs12: certs/server.p12
  tls_cert: certs/server.crt
  tls_key: certs/server.key
  # enable OpenSSL FIPS 140
  #fips: true
  # allow communcations without TLS
  allow_no_tls: true
  timeout: 10
auth:
  allow_anonymous: true
  password_file: psrt-passwd
  key_file: keys.yml
  acl: acl.yml
cluster:
  config: cluster.yml
