[target.x86_64-unknown-linux-musl]
rustflags = ["-Clink-arg=-s"]

[target.i686-unknown-linux-musl]
rustflags = ["-Clink-arg=-s"]

[target.arm-unknown-linux-musleabihf]
linker = "arm-linux-gnueabihf-ld"
rustflags = ["-Clink-arg=-s"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-Clink-arg=-s"]
